In [1]:
import torch
import gymnasium as gym
torch.cuda.set_device(0)

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

In [2]:
tt = torch.softmax(torch.randn(10,3), dim=-1)
tt = torch.tensor(
    [ [0.1, 0.2, 0.7],
        [2,5,5],
        [0.3, 0.4, 0.3]], dtype=torch.float32)
tt = torch.tensor(
    [ [1, 2, 3],
        [2,5,5],
        [3, 4, 3]], dtype=torch.float32)
print(tt.sum(dim=-1, ))
print(tt / tt.sum(dim=-1, keepdim=True))
print(torch.log(tt / tt.sum(dim=-1, keepdim=True))) 
dist = torch.distributions.Categorical(tt)
dist.log_prob(torch.tensor([2, 1, 1], dtype=torch.int64))
# dist.sample()
# print(torch.log(torch.tensor()))

tensor([ 6., 12., 10.])
tensor([[0.1667, 0.3333, 0.5000],
        [0.1667, 0.4167, 0.4167],
        [0.3000, 0.4000, 0.3000]])
tensor([[-1.7918, -1.0986, -0.6931],
        [-1.7918, -0.8755, -0.8755],
        [-1.2040, -0.9163, -1.2040]])


tensor([-0.6931, -0.8755, -0.9163])

In [3]:
torch.log(torch.tensor(0.0900))
probs = torch.tensor([0.1, 0.2, 0.8])
print(probs / probs.sum())
dist = torch.distributions.Categorical(probs)
sample = dist.sample()  # 随机采样一个类别
logp = dist.log_prob(torch.tensor(2))  # 计算类别2的对数概率
print(sample)
print(logp)
print(torch.log(torch.tensor(0.7273)))

tensor([0.0909, 0.1818, 0.7273])
tensor(2)
tensor(-0.3185)
tensor(-0.3184)


In [ ]:
env = gym.make('CartPole-v1', render_mode="human")
    # 获取状态和动作空间的维度
state_dim = env.observation_space.shape[0]  # 值为4，表示：
action_dim = env.action_space.n  # 值为2，表示：
state, _ = env.reset()         # 重置环境，获取初始状态
print(state)

[-0.02987477 -0.01096718 -0.01463353  0.03433904]


: 

In [5]:
tt = torch.tensor([
    [0.1, 0.2, 0.7],
    [1, 2, 7],
    ])
tt.std()
torch.min(tt, tt+torch.rand_like(tt) - 0.5)

tensor([[-0.2383,  0.2000,  0.7000],
        [ 1.0000,  1.5717,  6.8711]])